name: Compile with SourceMod

on:
  pull_request:
    branches: master
  push:
    branches: master

env:
  SOURCEMOD_PATH: $GITHUB_WORKSPACE
  SCRIPTS_PAT: $SOURCEMOD_PATH/addons/sourcemod/scripting

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SM_VERSION: ["1.10", "1.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.SM_VERSION }}

      - name: Compile plugins
        run: |
          for file in zones_*.sp
          do
            echo -e "\nCompiling $file..."
            spcomp -E -w234 -O2 -v2 -i $SCRIPTS_PATH/include $file
          done
        working-directory: ${{ env.SCRIPTS_PATH }}/
